// Prices are in INR. "image" points at a static file served by the frontend
// (public/images/products/<slug>.jpg) — see that folder's CREDITS.md for attribution.
export const seedProducts = [
  {
    slug: "gulab-jamun",
    name: "Gulab Jamun",
    category: "Milk Sweets",
    description: "Soft, deep-fried khoya dumplings soaked in warm rose-cardamom sugar syrup.",
    image: "/images/products/gulab-jamun.jpg",
    ingredients: ["Khoya (milk solids)","Refined flour","Sugar syrup","Cardamom","Rose water"],
    weightOptions: [{"label":"6 pieces","price":130},{"label":"12 pieces","price":240},{"label":"24 pieces","price":450}],
    shelfLife: "5-7 days, refrigerated",
    shape: "ball",
    fill: "brown",
    tone: "from-rose-100 to-amber-200",
    stock: 25,
    rating: 4.9,
    featured: true,
    specialty: false,
  },
  {
    slug: "rasgulla",
    name: "Rasgulla",
    category: "Milk Sweets",
    description: "Spongy cottage-cheese balls simmered in light, fragrant sugar syrup.",
    image: "/images/products/rasgulla.jpg",
    ingredients: ["Fresh chenna (cottage cheese)","Sugar syrup","Cardamom"],
    weightOptions: [{"label":"6 pieces","price":120},{"label":"12 pieces","price":220},{"label":"24 pieces","price":400}],
    shelfLife: "2-3 days, refrigerated",
    shape: "whiteBall",
    fill: "white",
    tone: "from-rose-100 to-amber-200",
    stock: 32,
    rating: 4.7,
    featured: false,
    specialty: false,
  },
  {
    slug: "rasmalai",
    name: "Rasmalai",
    category: "Milk Sweets",
    description: "Soft chenna discs soaked in chilled saffron-pistachio rabri.",
    image: "/images/products/rasmalai.jpg",
    ingredients: ["Fresh chenna","Reduced milk (rabri)","Sugar","Saffron","Pistachio"],
    weightOptions: [{"label":"6 pieces","price":160},{"label":"12 pieces","price":300},{"label":"24 pieces","price":560}],
    shelfLife: "2-3 days, refrigerated",
    shape: "whiteBall",
    fill: "white",
    tone: "from-rose-100 to-amber-200",
    stock: 39,
    rating: 4.9,
    featured: true,
    specialty: false,
  },
  {
    slug: "cham-cham",
    name: "Cham Cham",
    category: "Milk Sweets",
    description: "Oblong chenna sweets soaked in syrup and finished with coconut and saffron.",
    image: "/images/products/cham-cham.jpg",
    ingredients: ["Fresh chenna","Sugar syrup","Coconut","Saffron"],
    weightOptions: [{"label":"6 pieces","price":130},{"label":"12 pieces","price":240}],
    shelfLife: "2-3 days, refrigerated",
    shape: "whiteBall",
    fill: "white",
    tone: "from-rose-100 to-amber-200",
    stock: 46,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "sandesh",
    name: "Sandesh",
    category: "Milk Sweets",
    description: "Delicate Bengali chenna sweet, lightly sweetened and scented with cardamom.",
    image: "/images/products/sandesh.jpg",
    ingredients: ["Fresh chenna","Sugar","Cardamom","Saffron"],
    weightOptions: [{"label":"250g","price":190},{"label":"500g","price":350}],
    shelfLife: "2-3 days, refrigerated",
    shape: "disc",
    fill: "white",
    tone: "from-rose-100 to-amber-200",
    stock: 53,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "kharvas",
    name: "Kharvas",
    category: "Milk Sweets",
    description: "Steamed colostrum milk pudding, a delicate Maharashtrian specialty.",
    image: "/images/products/kharvas.jpg",
    ingredients: ["Fresh cow colostrum milk","Sugar","Cardamom","Nutmeg"],
    weightOptions: [{"label":"250g","price":170},{"label":"500g","price":320}],
    shelfLife: "2 days, refrigerated",
    shape: "square",
    fill: "white",
    tone: "from-rose-100 to-amber-200",
    stock: 60,
    rating: 4.5,
    featured: false,
    specialty: false,
  },
  {
    slug: "jalebi",
    name: "Jalebi",
    category: "Fried & Syrup",
    description: "Crisp, coiled batter fritters soaked in saffron sugar syrup, fried fresh to order.",
    image: "/images/products/jalebi.jpg",
    ingredients: ["Refined flour","Yogurt","Sugar syrup","Saffron","Ghee for frying"],
    weightOptions: [{"label":"250g","price":140},{"label":"500g","price":260},{"label":"1kg","price":480}],
    shelfLife: "3-4 days, room temperature",
    shape: "spiral",
    fill: "orange",
    tone: "from-orange-500 to-red-600",
    stock: 27,
    rating: 4.8,
    featured: true,
    specialty: false,
  },
  {
    slug: "jangiri-imarti",
    name: "Jangiri / Imarti",
    category: "Fried & Syrup",
    description: "Crisp, coiled urad-dal fritters soaked in saffron syrup.",
    image: "/images/products/jangiri-imarti.jpg",
    ingredients: ["Urad dal batter","Sugar syrup","Saffron","Ghee for frying"],
    weightOptions: [{"label":"250g","price":150},{"label":"500g","price":280}],
    shelfLife: "3-4 days, room temperature",
    shape: "spiral",
    fill: "red",
    tone: "from-orange-500 to-red-600",
    stock: 34,
    rating: 4.5,
    featured: false,
    specialty: false,
  },
  {
    slug: "balushahi",
    name: "Balushahi",
    category: "Fried & Syrup",
    description: "Flaky, glazed pastry rounds soaked in light sugar syrup.",
    image: "/images/products/balushahi.jpg",
    ingredients: ["Refined flour","Ghee","Yogurt","Sugar syrup"],
    weightOptions: [{"label":"250g","price":150},{"label":"500g","price":280},{"label":"1kg","price":520}],
    shelfLife: "5-6 days, room temperature",
    shape: "disc",
    fill: "golden",
    tone: "from-orange-500 to-red-600",
    stock: 41,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "malpua",
    name: "Malpua",
    category: "Fried & Syrup",
    description: "Golden pan-fried pancakes soaked in fennel-scented sugar syrup.",
    image: "/images/products/malpua.jpg",
    ingredients: ["Refined flour","Khoya","Fennel seeds","Sugar syrup","Ghee for frying"],
    weightOptions: [{"label":"4 pieces","price":120},{"label":"8 pieces","price":220}],
    shelfLife: "2-3 days, refrigerated",
    shape: "disc",
    fill: "golden",
    tone: "from-orange-500 to-red-600",
    stock: 48,
    rating: 4.5,
    featured: false,
    specialty: false,
  },
  {
    slug: "kaju-katli",
    name: "Kaju Katli",
    category: "Barfi & Katli",
    description: "Diamond-cut cashew fudge finished with a delicate layer of silver vark.",
    image: "/images/products/kaju-katli.jpg",
    ingredients: ["Cashew nuts","Sugar","Ghee","Silver vark"],
    weightOptions: [{"label":"250g","price":280},{"label":"500g","price":540},{"label":"1kg","price":1020}],
    shelfLife: "15 days, room temperature",
    shape: "diamond",
    fill: "silver",
    tone: "from-amber-300 to-yellow-500",
    stock: 55,
    rating: 4.9,
    featured: true,
    specialty: false,
  },
  {
    slug: "milk-barfi",
    name: "Milk Barfi",
    category: "Barfi & Katli",
    description: "Dense, creamy milk fudge set with cardamom and a scatter of pistachio.",
    image: "/images/products/milk-barfi.jpg",
    ingredients: ["Khoya (milk solids)","Sugar","Cardamom","Pistachio"],
    weightOptions: [{"label":"250g","price":180},{"label":"500g","price":340},{"label":"1kg","price":640}],
    shelfLife: "10-12 days, room temperature",
    shape: "square",
    fill: "white",
    tone: "from-amber-300 to-yellow-500",
    stock: 62,
    rating: 4.7,
    featured: false,
    specialty: false,
  },
  {
    slug: "coconut-barfi",
    name: "Coconut Barfi",
    category: "Barfi & Katli",
    description: "Fresh grated coconut fudge, lightly sweetened and cut into soft squares.",
    image: "/images/products/coconut-barfi.jpg",
    ingredients: ["Fresh grated coconut","Khoya","Sugar","Cardamom"],
    weightOptions: [{"label":"250g","price":170},{"label":"500g","price":320},{"label":"1kg","price":600}],
    shelfLife: "10-12 days, room temperature",
    shape: "square",
    fill: "green",
    tone: "from-amber-300 to-yellow-500",
    stock: 29,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "mawa-cake",
    name: "Mawa Cake",
    category: "Barfi & Katli",
    description: "Soft, khoya-rich cake with a delicate cardamom crumb.",
    image: "/images/products/mawa-cake.jpg",
    ingredients: ["Khoya","Refined flour","Sugar","Cardamom","Ghee"],
    weightOptions: [{"label":"500g","price":320},{"label":"1kg","price":600}],
    shelfLife: "5-6 days, room temperature",
    shape: "square",
    fill: "golden",
    tone: "from-amber-300 to-yellow-500",
    stock: 36,
    rating: 4.5,
    featured: false,
    specialty: false,
  },
  {
    slug: "kalakand",
    name: "Kalakand",
    category: "Barfi & Katli",
    description: "Grainy milk fudge made from fresh chenna, lightly sweetened and topped with pistachio.",
    image: "/images/products/kalakand.jpg",
    ingredients: ["Fresh chenna","Khoya","Sugar","Cardamom","Pistachio"],
    weightOptions: [{"label":"250g","price":190},{"label":"500g","price":360},{"label":"1kg","price":680}],
    shelfLife: "7-8 days, refrigerated",
    shape: "square",
    fill: "white",
    tone: "from-amber-300 to-yellow-500",
    stock: 43,
    rating: 4.7,
    featured: false,
    specialty: false,
  },
  {
    slug: "motichoor-laddu",
    name: "Motichoor Laddu",
    category: "Laddu",
    description: "Tiny gram-flour pearls bound in ghee and sugar syrup, rolled into golden balls.",
    image: "/images/products/motichoor-laddu.jpg",
    ingredients: ["Gram flour (besan) pearls","Ghee","Sugar syrup","Cardamom","Almonds"],
    weightOptions: [{"label":"6 pieces","price":130},{"label":"12 pieces","price":240},{"label":"1kg","price":620}],
    shelfLife: "10-12 days, room temperature",
    shape: "ball",
    fill: "golden",
    tone: "from-orange-400 to-amber-600",
    stock: 50,
    rating: 4.8,
    featured: true,
    specialty: false,
  },
  {
    slug: "besan-laddu",
    name: "Besan Laddu",
    category: "Laddu",
    description: "Roasted gram flour laddus rich with ghee, cardamom, and a nutty finish.",
    image: "/images/products/besan-laddu.jpg",
    ingredients: ["Roasted gram flour","Ghee","Powdered sugar","Cardamom"],
    weightOptions: [{"label":"6 pieces","price":120},{"label":"12 pieces","price":220},{"label":"1kg","price":560}],
    shelfLife: "12-15 days, room temperature",
    shape: "ball",
    fill: "golden",
    tone: "from-orange-400 to-amber-600",
    stock: 57,
    rating: 4.7,
    featured: false,
    specialty: false,
  },
  {
    slug: "boondi-laddu",
    name: "Boondi Laddu",
    category: "Laddu",
    description: "Classic boondi pearls bound with sugar syrup, raisins, and cardamom.",
    image: "/images/products/boondi-laddu.jpg",
    ingredients: ["Gram flour boondi","Ghee","Sugar syrup","Cardamom","Raisins"],
    weightOptions: [{"label":"6 pieces","price":120},{"label":"12 pieces","price":220},{"label":"1kg","price":560}],
    shelfLife: "10-12 days, room temperature",
    shape: "ball",
    fill: "golden",
    tone: "from-orange-400 to-amber-600",
    stock: 64,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "til-laddu",
    name: "Til Laddu",
    category: "Laddu",
    description: "Roasted sesame and jaggery laddus, a nutty winter favorite.",
    image: "/images/products/til-laddu.jpg",
    ingredients: ["Roasted sesame seeds","Jaggery","Cardamom"],
    weightOptions: [{"label":"6 pieces","price":110},{"label":"12 pieces","price":200}],
    shelfLife: "15-20 days, room temperature",
    shape: "ball",
    fill: "brown",
    tone: "from-orange-400 to-amber-600",
    stock: 31,
    rating: 4.5,
    featured: false,
    specialty: false,
  },
  {
    slug: "dharwad-peda",
    name: "Dharwad Peda",
    category: "Peda",
    description: "Caramelized khoya fudge from Karnataka, slow-cooked to a rich amber hue.",
    image: "/images/products/dharwad-peda.jpg",
    ingredients: ["Khoya (milk solids)","Sugar","Cardamom"],
    weightOptions: [{"label":"250g","price":180},{"label":"500g","price":340},{"label":"1kg","price":640}],
    shelfLife: "10 days, room temperature",
    shape: "disc",
    fill: "golden",
    tone: "from-amber-400 to-orange-500",
    stock: 38,
    rating: 4.7,
    featured: false,
    specialty: false,
  },
  {
    slug: "carrot-halwa",
    name: "Carrot Halwa",
    category: "Halwa",
    description: "Slow-simmered carrots in milk and ghee, finished with cashews and raisins.",
    image: "/images/products/carrot-halwa.jpg",
    ingredients: ["Fresh carrots","Milk","Ghee","Sugar","Cashews & raisins"],
    weightOptions: [{"label":"250g","price":180},{"label":"500g","price":340},{"label":"1kg","price":640}],
    shelfLife: "4-5 days, refrigerated",
    shape: "bowl",
    fill: "orange",
    tone: "from-orange-500 to-red-500",
    stock: 45,
    rating: 4.8,
    featured: false,
    specialty: false,
  },
  {
    slug: "badam-halwa",
    name: "Badam Halwa",
    category: "Halwa",
    description: "Rich almond halwa slow-cooked in ghee with saffron and cardamom.",
    image: "/images/products/badam-halwa.jpg",
    ingredients: ["Almonds","Ghee","Sugar","Saffron","Cardamom"],
    weightOptions: [{"label":"250g","price":320},{"label":"500g","price":600},{"label":"1kg","price":1120}],
    shelfLife: "7 days, refrigerated",
    shape: "bowl",
    fill: "brown",
    tone: "from-orange-500 to-red-500",
    stock: 52,
    rating: 4.8,
    featured: false,
    specialty: false,
  },
  {
    slug: "moong-dal-halwa",
    name: "Moong Dal Halwa",
    category: "Halwa",
    description: "Split moong lentils simmered in ghee to a glossy, nutty halwa.",
    image: "/images/products/moong-dal-halwa.jpg",
    ingredients: ["Split moong lentils","Ghee","Sugar","Khoya","Cardamom"],
    weightOptions: [{"label":"250g","price":220},{"label":"500g","price":420},{"label":"1kg","price":780}],
    shelfLife: "5-6 days, refrigerated",
    shape: "bowl",
    fill: "golden",
    tone: "from-orange-500 to-red-500",
    stock: 59,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "double-ka-meetha",
    name: "Double Ka Meetha",
    category: "Halwa",
    description: "Hyderabadi bread pudding, fried and soaked in saffron milk.",
    image: "/images/products/double-ka-meetha.jpg",
    ingredients: ["Bread","Ghee","Full-cream milk","Sugar","Dry fruits"],
    weightOptions: [{"label":"250ml","price":150},{"label":"500ml","price":280}],
    shelfLife: "2 days, refrigerated",
    shape: "bowl",
    fill: "brown",
    tone: "from-orange-500 to-red-500",
    stock: 26,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "qubani-ka-meetha",
    name: "Qubani Ka Meetha",
    category: "Halwa",
    description: "Stewed dried apricots served with fresh cream, a Hyderabadi classic.",
    image: "/images/products/qubani-ka-meetha.jpg",
    ingredients: ["Dried apricots","Sugar","Cardamom","Fresh cream"],
    weightOptions: [{"label":"250ml","price":170},{"label":"500ml","price":320}],
    shelfLife: "3-4 days, refrigerated",
    shape: "bowl",
    fill: "orange",
    tone: "from-orange-500 to-red-500",
    stock: 33,
    rating: 4.5,
    featured: false,
    specialty: false,
  },
  {
    slug: "rabri",
    name: "Rabri",
    category: "Creamy & Puddings",
    description: "Slow-reduced sweetened milk, layered and chilled to a rich, creamy finish.",
    image: "/images/products/rabri.jpg",
    ingredients: ["Full-cream milk","Sugar","Cardamom","Saffron","Pistachio"],
    weightOptions: [{"label":"250ml","price":180},{"label":"500ml","price":340}],
    shelfLife: "2 days, refrigerated",
    shape: "bowl",
    fill: "white",
    tone: "from-amber-100 to-orange-200",
    stock: 40,
    rating: 4.7,
    featured: false,
    specialty: false,
  },
  {
    slug: "shrikhand",
    name: "Shrikhand",
    category: "Creamy & Puddings",
    description: "Silky hung-curd dessert scented with saffron and cardamom.",
    image: "/images/products/shrikhand.jpg",
    ingredients: ["Hung curd (chakka)","Sugar","Saffron","Cardamom"],
    weightOptions: [{"label":"250ml","price":150},{"label":"500ml","price":280}],
    shelfLife: "3 days, refrigerated",
    shape: "bowl",
    fill: "white",
    tone: "from-amber-100 to-orange-200",
    stock: 47,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "basundi",
    name: "Basundi",
    category: "Creamy & Puddings",
    description: "Thick, slow-simmered sweetened milk finished with almonds and cardamom.",
    image: "/images/products/basundi.jpg",
    ingredients: ["Full-cream milk","Sugar","Cardamom","Almonds"],
    weightOptions: [{"label":"250ml","price":160},{"label":"500ml","price":300}],
    shelfLife: "2-3 days, refrigerated",
    shape: "bowl",
    fill: "white",
    tone: "from-amber-100 to-orange-200",
    stock: 54,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "phirni",
    name: "Phirni",
    category: "Creamy & Puddings",
    description: "Ground rice pudding set in clay bowls, scented with rose water and cardamom.",
    image: "/images/products/phirni.jpg",
    ingredients: ["Ground rice","Milk","Sugar","Cardamom","Rose water"],
    weightOptions: [{"label":"250ml","price":130},{"label":"500ml","price":240}],
    shelfLife: "2-3 days, refrigerated",
    shape: "bowl",
    fill: "white",
    tone: "from-amber-100 to-orange-200",
    stock: 61,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "kheer",
    name: "Kheer",
    category: "Creamy & Puddings",
    description: "Traditional rice pudding simmered slowly in milk with cardamom and nuts.",
    image: "/images/products/kheer.jpg",
    ingredients: ["Rice","Full-cream milk","Sugar","Cardamom","Nuts"],
    weightOptions: [{"label":"250ml","price":130},{"label":"500ml","price":240},{"label":"1L","price":440}],
    shelfLife: "2-3 days, refrigerated",
    shape: "bowl",
    fill: "white",
    tone: "from-amber-100 to-orange-200",
    stock: 28,
    rating: 4.8,
    featured: true,
    specialty: false,
  },
  {
    slug: "payasam",
    name: "Payasam",
    category: "Creamy & Puddings",
    description: "South Indian milk pudding simmered with vermicelli, jaggery, and roasted cashews — one of our South Indian specialties.",
    image: "/images/products/payasam.jpg",
    ingredients: ["Vermicelli or rice","Milk","Jaggery / Sugar","Ghee","Cashews"],
    weightOptions: [{"label":"250ml","price":140},{"label":"500ml","price":260}],
    shelfLife: "2-3 days, refrigerated",
    shape: "bowl",
    fill: "white",
    tone: "from-amber-100 to-orange-200",
    stock: 35,
    rating: 4.7,
    featured: true,
    specialty: true,
  },
  {
    slug: "modak",
    name: "Modak",
    category: "Steamed & Dumplings",
    description: "Steamed rice-flour dumplings filled with jaggery and fresh coconut.",
    image: "/images/products/modak.jpg",
    ingredients: ["Rice flour","Fresh coconut","Jaggery","Cardamom"],
    weightOptions: [{"label":"6 pieces","price":160},{"label":"12 pieces","price":300}],
    shelfLife: "1-2 days, refrigerated",
    shape: "cone",
    fill: "cream",
    tone: "from-emerald-200 to-teal-400",
    stock: 42,
    rating: 4.7,
    featured: false,
    specialty: false,
  },
  {
    slug: "kozhukattai",
    name: "Kozhukattai",
    category: "Steamed & Dumplings",
    description: "Soft steamed rice dumplings with a sweet coconut-jaggery filling.",
    image: "/images/products/kozhukattai.jpg",
    ingredients: ["Rice flour","Coconut","Jaggery","Cardamom"],
    weightOptions: [{"label":"6 pieces","price":150},{"label":"12 pieces","price":280}],
    shelfLife: "1-2 days, refrigerated",
    shape: "cone",
    fill: "cream",
    tone: "from-emerald-200 to-teal-400",
    stock: 49,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "unniyappam",
    name: "Unniyappam",
    category: "Steamed & Dumplings",
    description: "Small fried rice-jaggery fritters with banana and coconut.",
    image: "/images/products/unniyappam.jpg",
    ingredients: ["Rice flour","Jaggery","Banana","Coconut","Ghee for frying"],
    weightOptions: [{"label":"6 pieces","price":120},{"label":"12 pieces","price":220}],
    shelfLife: "2-3 days, room temperature",
    shape: "ball",
    fill: "brown",
    tone: "from-emerald-200 to-teal-400",
    stock: 56,
    rating: 4.5,
    featured: false,
    specialty: false,
  },
  {
    slug: "soan-papdi",
    name: "Soan Papdi",
    category: "Flaky & Layered",
    description: "Delicate, flaky gram-flour threads that melt away with the first bite.",
    image: "/images/products/soan-papdi.jpg",
    ingredients: ["Gram flour","Sugar syrup","Ghee","Cardamom","Pistachio"],
    weightOptions: [{"label":"250g","price":140},{"label":"500g","price":260},{"label":"1kg","price":480}],
    shelfLife: "15 days, room temperature",
    shape: "bar",
    fill: "golden",
    tone: "from-yellow-300 to-amber-400",
    stock: 63,
    rating: 4.5,
    featured: false,
    specialty: false,
  },
  {
    slug: "khaja",
    name: "Khaja",
    category: "Flaky & Layered",
    description: "Multi-layered flaky pastry, fried crisp and dipped in sugar syrup.",
    image: "/images/products/khaja.jpg",
    ingredients: ["Refined flour","Sugar syrup","Ghee"],
    weightOptions: [{"label":"250g","price":150},{"label":"500g","price":280}],
    shelfLife: "10 days, room temperature",
    shape: "bar",
    fill: "golden",
    tone: "from-yellow-300 to-amber-400",
    stock: 30,
    rating: 4.5,
    featured: false,
    specialty: false,
  },
  {
    slug: "pootharekulu",
    name: "Pootharekulu",
    category: "Flaky & Layered",
    description: "Paper-thin rice starch sheets layered with ghee and powdered sugar.",
    image: "/images/products/pootharekulu.jpg",
    ingredients: ["Rice starch sheets","Ghee","Powdered sugar","Dry fruits"],
    weightOptions: [{"label":"6 pieces","price":170},{"label":"12 pieces","price":320}],
    shelfLife: "20 days, airtight container",
    shape: "bar",
    fill: "cream",
    tone: "from-yellow-300 to-amber-400",
    stock: 37,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "ghevar",
    name: "Ghevar",
    category: "Festive Specials",
    description: "Crisp, disc-shaped lattice pastry soaked in syrup and topped with rabri.",
    image: "/images/products/ghevar.jpg",
    ingredients: ["Refined flour","Ghee","Sugar syrup","Rabri","Pistachio"],
    weightOptions: [{"label":"1 piece","price":160},{"label":"4 pieces","price":560}],
    shelfLife: "5-7 days, room temperature",
    shape: "lattice",
    fill: "golden",
    tone: "from-red-500 to-rose-700",
    stock: 44,
    rating: 4.8,
    featured: true,
    specialty: false,
  },
  {
    slug: "gujiya",
    name: "Gujiya",
    category: "Festive Specials",
    description: "Golden fried pastry pockets filled with khoya and dry fruits.",
    image: "/images/products/gujiya.jpg",
    ingredients: ["Refined flour","Khoya","Dry fruits","Sugar","Ghee for frying"],
    weightOptions: [{"label":"6 pieces","price":150},{"label":"12 pieces","price":280}],
    shelfLife: "7-10 days, airtight container",
    shape: "crescent",
    fill: "golden",
    tone: "from-red-500 to-rose-700",
    stock: 51,
    rating: 4.7,
    featured: false,
    specialty: false,
  },
  {
    slug: "anarsa",
    name: "Anarsa",
    category: "Festive Specials",
    description: "Crisp, jaggery-sweetened rice discs coated in sesame seeds.",
    image: "/images/products/anarsa.jpg",
    ingredients: ["Rice flour","Jaggery","Sesame seeds","Ghee for frying"],
    weightOptions: [{"label":"6 pieces","price":130},{"label":"12 pieces","price":240}],
    shelfLife: "7-10 days, airtight container",
    shape: "disc",
    fill: "brown",
    tone: "from-red-500 to-rose-700",
    stock: 58,
    rating: 4.5,
    featured: false,
    specialty: false,
  },
  {
    slug: "ariselu",
    name: "Ariselu",
    category: "Festive Specials",
    description: "Andhra festive sweet made from rice flour and jaggery, deep-fried to a crisp finish.",
    image: "/images/products/ariselu.jpg",
    ingredients: ["Rice flour","Jaggery","Sesame seeds","Ghee for frying"],
    weightOptions: [{"label":"6 pieces","price":130},{"label":"12 pieces","price":240}],
    shelfLife: "7-10 days, airtight container",
    shape: "disc",
    fill: "brown",
    tone: "from-red-500 to-rose-700",
    stock: 25,
    rating: 4.4,
    featured: false,
    specialty: false,
  },
  {
    slug: "adhirasam",
    name: "Adhirasam",
    category: "Festive Specials",
    description: "Deep-fried jaggery-rice discs, dense and delicately sweet.",
    image: "/images/products/adhirasam.jpg",
    ingredients: ["Rice flour","Jaggery","Cardamom","Ghee for frying"],
    weightOptions: [{"label":"6 pieces","price":130},{"label":"12 pieces","price":240}],
    shelfLife: "7-10 days, airtight container",
    shape: "disc",
    fill: "brown",
    tone: "from-red-500 to-rose-700",
    stock: 32,
    rating: 4.4,
    featured: false,
    specialty: false,
  },
  {
    slug: "chikki",
    name: "Chikki",
    category: "Festive Specials",
    description: "Crunchy peanut and jaggery brittle, made in small batches.",
    image: "/images/products/chikki.jpg",
    ingredients: ["Peanuts","Jaggery","Ghee"],
    weightOptions: [{"label":"250g","price":110},{"label":"500g","price":200},{"label":"1kg","price":380}],
    shelfLife: "20-25 days, room temperature",
    shape: "bar",
    fill: "brown",
    tone: "from-red-500 to-rose-700",
    stock: 39,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "poli-puran-poli",
    name: "Poli / Puran Poli",
    category: "South Indian Classics",
    description: "Sweet lentil-stuffed flatbread, pan-roasted in ghee.",
    image: "/images/products/poli-puran-poli.jpg",
    ingredients: ["Chana dal","Jaggery","Refined flour","Cardamom","Ghee"],
    weightOptions: [{"label":"2 pieces","price":130},{"label":"4 pieces","price":240}],
    shelfLife: "3-4 days, room temperature",
    shape: "flatbread",
    fill: "golden",
    tone: "from-amber-500 to-orange-700",
    stock: 46,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "obbattu-holige",
    name: "Obbattu / Holige",
    category: "South Indian Classics",
    description: "Karnataka-style sweet flatbread filled with jaggery and chana dal.",
    image: "/images/products/obbattu-holige.jpg",
    ingredients: ["Chana dal","Jaggery","Refined flour","Cardamom","Ghee"],
    weightOptions: [{"label":"2 pieces","price":130},{"label":"4 pieces","price":240}],
    shelfLife: "3-4 days, room temperature",
    shape: "flatbread",
    fill: "golden",
    tone: "from-amber-500 to-orange-700",
    stock: 53,
    rating: 4.6,
    featured: false,
    specialty: false,
  },
  {
    slug: "mysore-pak",
    name: "Mysore Pak",
    category: "South Indian Classics",
    description: "Melt-in-the-mouth gram flour fudge, slow-cooked in generous ghee — a South Indian specialty from Karnataka.",
    image: "/images/products/mysore-pak.jpg",
    ingredients: ["Gram flour","Ghee","Sugar"],
    weightOptions: [{"label":"250g","price":200},{"label":"500g","price":380},{"label":"1kg","price":720}],
    shelfLife: "12-15 days, room temperature",
    shape: "square",
    fill: "golden",
    tone: "from-amber-500 to-orange-700",
    stock: 60,
    rating: 4.8,
    featured: true,
    specialty: true,
  },
  {
    slug: "a2-bilona-desi-ghee",
    name: "A2 Bilona Desi Ghee",
    category: "Pure Ghee",
    description: "Hand-churned using the traditional bilona method from A2 cow milk curd — rich, grainy, and deeply aromatic. Our signature ghee.",
    image: "/images/products/a2-bilona-desi-ghee.jpg",
    ingredients: ["A2 cow milk","Cultured curd"],
    weightOptions: [{"label":"200ml","price":450},{"label":"500ml","price":950},{"label":"1L","price":1800}],
    shelfLife: "12 months, room temperature",
    shape: "jar",
    fill: "golden",
    tone: "from-yellow-300 to-amber-700",
    stock: 27,
    rating: 5,
    featured: true,
    specialty: true,
  },
  {
    slug: "pure-cow-ghee",
    name: "Pure Cow Ghee",
    category: "Pure Ghee",
    description: "Slow-simmered pure cow ghee with a rich golden colour and classic nutty aroma, perfect for everyday cooking and sweets.",
    image: "/images/products/pure-cow-ghee.jpg",
    ingredients: ["Cow milk cream"],
    weightOptions: [{"label":"200ml","price":350},{"label":"500ml","price":750},{"label":"1L","price":1400}],
    shelfLife: "12 months, room temperature",
    shape: "jar",
    fill: "golden",
    tone: "from-yellow-300 to-amber-700",
    stock: 34,
    rating: 4.9,
    featured: true,
    specialty: true,
  },
  {
    slug: "buffalo-ghee",
    name: "Buffalo Ghee",
    category: "Pure Ghee",
    description: "Thick, richly textured buffalo milk ghee with a deep aroma — a favourite for festive halwas and laddus.",
    image: "/images/products/buffalo-ghee.jpg",
    ingredients: ["Buffalo milk cream"],
    weightOptions: [{"label":"200ml","price":280},{"label":"500ml","price":600},{"label":"1L","price":1100}],
    shelfLife: "12 months, room temperature",
    shape: "jar",
    fill: "cream",
    tone: "from-yellow-300 to-amber-700",
    stock: 41,
    rating: 4.8,
    featured: false,
    specialty: true,
  }
];
